# AntaresOS · starship.toml — Matrix

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$directory\
[](fg:surface0 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface2)\
$dart\
$nodejs\
$python\
[](fg:surface2 bg:none)\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "antares_matrix"

[fill]
symbol = " "

[os]
disabled = false
style = "bg:surface0 fg:green"
[os.symbols]
Macos = "󰀵 "

[directory]
style = "bg:surface0 fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Github" = " "
"AntaresOS" = "✦ "

[git_branch]
symbol = ""
style = "bg:surface1 fg:cyan"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:surface1 fg:red"
format = '[$all_status$ahead_behind ]($style)'

[dart]
symbol = ""
style = "bg:surface2 fg:sky"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:surface2 fg:green"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:surface2 fg:amber"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 500
style = "fg:dim"
format = '[  $duration ]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold amber)"

[palettes.antares_matrix]
green = "#00ff41"
text = "#7cffa0"
bright = "#c8ffd4"
dim = "#2e6b3e"
cyan = "#48ffe0"
sky = "#35c9ff"
amber = "#f5d76e"
magenta = "#ff6fd8"
red = "#ff4d4d"
surface2 = "#14371f"
surface1 = "#0f230f"
surface0 = "#0b140b"
base = "#000000"
