# AntaresOS · starship.toml — Ice Black

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$directory\
[](fg:surface0 bg:surface1)\
$git_branch\
$git_status\
[](fg:surface1 bg:surface2)\
$dart\
$kotlin\
$java\
$nodejs\
$python\
$docker_context\
[](fg:surface2 bg:none)\
$fill\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = "ice_black"

[fill]
symbol = " "

[os]
disabled = false
style = "bg:surface0 fg:ice"
[os.symbols]
Macos = "󰀵 "

[directory]
style = "bg:surface0 fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Github" = " "
"AntaresOS" = "✦ "

[git_branch]
symbol = ""
style = "bg:surface1 fg:ice"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:surface1 fg:orange"
format = '[$all_status$ahead_behind ]($style)'

[dart]
symbol = ""
style = "bg:surface2 fg:sky"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ""
style = "bg:surface2 fg:magenta"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:surface2 fg:red"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:surface2 fg:sky"
format = '[ $symbol$context ]($style)'
only_with_files = true

[nodejs]
symbol = ""
style = "bg:surface2 fg:sky"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:surface2 fg:orange"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
min_time = 500
style = "fg:dim"
format = '[  $duration ]($style)'

[character]
success_symbol = "[❯](bold ice)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold orange)"

[palettes.ice_black]
ice     = "#3dc9e9"
text    = "#b0c9e8"
bright  = "#60d8f8"
dim     = "#3a5070"
blue    = "#4f9cf9"
sky     = "#70b4ff"
orange  = "#ffb454"
magenta = "#c77dff"
red     = "#ff4560"
green   = "#3dd68c"
surface2 = "#111d2e"
surface1 = "#0f1a28"
surface0 = "#0c1520"
base    = "#080d14"
